[project]
name = "molde"
version = "0.1.18"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["vtk>=9.3.1", "numpy>=2.0.0", "moviepy>=1.0.0", "qtpy>=2.4.2"]

[dependency-groups]
dev = ["pymupdf>=1.27.2.3", "pyside6>=6.11.1", "ruff>=0.15.18"]

[project.scripts]
logos = "scripts.convert:main"

[tool.ruff]
exclude = ["__pycache__", "vibra/interface/ui_generated"]
line-length = 150

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
